// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/mfa/v1/deliver_code.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliverCodeRequest struct {
	// foreign key referencing code
	CodeId string `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	// Types that are valid to be assigned to CodeRecipient:
	//	*DeliverCodeRequest_EmailAddressId
	//	*DeliverCodeRequest_PhoneNumberId
	CodeRecipient        isDeliverCodeRequest_CodeRecipient `protobuf_oneof:"code_recipient"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *DeliverCodeRequest) Reset()         { *m = DeliverCodeRequest{} }
func (m *DeliverCodeRequest) String() string { return proto.CompactTextString(m) }
func (*DeliverCodeRequest) ProtoMessage()    {}
func (*DeliverCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac38adea13cc5907, []int{0}
}

func (m *DeliverCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverCodeRequest.Unmarshal(m, b)
}
func (m *DeliverCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverCodeRequest.Marshal(b, m, deterministic)
}
func (m *DeliverCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverCodeRequest.Merge(m, src)
}
func (m *DeliverCodeRequest) XXX_Size() int {
	return xxx_messageInfo_DeliverCodeRequest.Size(m)
}
func (m *DeliverCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverCodeRequest proto.InternalMessageInfo

func (m *DeliverCodeRequest) GetCodeId() string {
	if m != nil {
		return m.CodeId
	}
	return ""
}

type isDeliverCodeRequest_CodeRecipient interface {
	isDeliverCodeRequest_CodeRecipient()
}

type DeliverCodeRequest_EmailAddressId struct {
	EmailAddressId string `protobuf:"bytes,2,opt,name=email_address_id,json=emailAddressId,proto3,oneof"`
}

type DeliverCodeRequest_PhoneNumberId struct {
	PhoneNumberId string `protobuf:"bytes,3,opt,name=phone_number_id,json=phoneNumberId,proto3,oneof"`
}

func (*DeliverCodeRequest_EmailAddressId) isDeliverCodeRequest_CodeRecipient() {}

func (*DeliverCodeRequest_PhoneNumberId) isDeliverCodeRequest_CodeRecipient() {}

func (m *DeliverCodeRequest) GetCodeRecipient() isDeliverCodeRequest_CodeRecipient {
	if m != nil {
		return m.CodeRecipient
	}
	return nil
}

func (m *DeliverCodeRequest) GetEmailAddressId() string {
	if x, ok := m.GetCodeRecipient().(*DeliverCodeRequest_EmailAddressId); ok {
		return x.EmailAddressId
	}
	return ""
}

func (m *DeliverCodeRequest) GetPhoneNumberId() string {
	if x, ok := m.GetCodeRecipient().(*DeliverCodeRequest_PhoneNumberId); ok {
		return x.PhoneNumberId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeliverCodeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeliverCodeRequest_EmailAddressId)(nil),
		(*DeliverCodeRequest_PhoneNumberId)(nil),
	}
}

type DeliverCodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverCodeResponse) Reset()         { *m = DeliverCodeResponse{} }
func (m *DeliverCodeResponse) String() string { return proto.CompactTextString(m) }
func (*DeliverCodeResponse) ProtoMessage()    {}
func (*DeliverCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac38adea13cc5907, []int{1}
}

func (m *DeliverCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverCodeResponse.Unmarshal(m, b)
}
func (m *DeliverCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverCodeResponse.Marshal(b, m, deterministic)
}
func (m *DeliverCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverCodeResponse.Merge(m, src)
}
func (m *DeliverCodeResponse) XXX_Size() int {
	return xxx_messageInfo_DeliverCodeResponse.Size(m)
}
func (m *DeliverCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverCodeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeliverCodeRequest)(nil), "alpacalabs.mfa.v1.DeliverCodeRequest")
	proto.RegisterType((*DeliverCodeResponse)(nil), "alpacalabs.mfa.v1.DeliverCodeResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/mfa/v1/deliver_code.proto", fileDescriptor_ac38adea13cc5907)
}

var fileDescriptor_ac38adea13cc5907 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xf3, 0x30,
	0x1c, 0xc6, 0xdf, 0x6e, 0xb0, 0x57, 0x03, 0xce, 0xad, 0x32, 0xf4, 0x28, 0xc3, 0xc3, 0x10, 0x96,
	0x52, 0xbc, 0x78, 0xdd, 0xf4, 0xe0, 0x60, 0x95, 0xd1, 0xc3, 0x0e, 0x32, 0x28, 0xff, 0x36, 0xff,
	0x6c, 0x81, 0xa6, 0x89, 0x49, 0xdb, 0x2f, 0xe1, 0xd9, 0x2f, 0xe0, 0xd1, 0x8f, 0xe2, 0xa7, 0x92,
	0x64, 0xc2, 0x94, 0x1d, 0xf3, 0x3c, 0xbf, 0x27, 0xc9, 0xf3, 0x90, 0x1b, 0x28, 0x35, 0x14, 0x50,
	0x42, 0x6e, 0x23, 0xc9, 0x21, 0x6a, 0xe3, 0x88, 0x61, 0x29, 0x5a, 0x34, 0x59, 0xa1, 0x18, 0x52,
	0x6d, 0x54, 0xad, 0xc2, 0xe1, 0x81, 0xa2, 0x92, 0x03, 0x6d, 0xe3, 0xf1, 0x7b, 0x40, 0xc2, 0xc7,
	0x3d, 0xf9, 0xa0, 0x18, 0xa6, 0xf8, 0xda, 0xa0, 0xad, 0xc3, 0x4b, 0xf2, 0xdf, 0xe5, 0x32, 0xc1,
	0xae, 0x82, 0xeb, 0x60, 0x72, 0x9a, 0xf6, 0xdc, 0x71, 0xc1, 0xc2, 0x5b, 0x32, 0x40, 0x09, 0xa2,
	0xcc, 0x80, 0x31, 0x83, 0xd6, 0x3a, 0xa2, 0xe3, 0x88, 0xa7, 0x7f, 0x69, 0xdf, 0x3b, 0xb3, 0xbd,
	0xb1, 0x60, 0xe1, 0x84, 0x9c, 0xeb, 0x9d, 0xaa, 0x30, 0xab, 0x1a, 0x99, 0xa3, 0x71, 0x68, 0xf7,
	0x07, 0x3d, 0xf3, 0xc6, 0xb3, 0xd7, 0x17, 0x6c, 0x3e, 0x20, 0x7d, 0xff, 0x9c, 0xc1, 0x42, 0x68,
	0x81, 0x55, 0x3d, 0x1e, 0x91, 0x8b, 0x3f, 0xdf, 0xb2, 0x5a, 0x55, 0x16, 0xe7, 0x6f, 0x01, 0x19,
	0x15, 0x4a, 0xd2, 0xa3, 0x22, 0xf3, 0x93, 0x84, 0xc3, 0xca, 0xb5, 0x5c, 0x05, 0x2f, 0xf7, 0x5b,
	0x51, 0xef, 0x9a, 0x9c, 0x16, 0x4a, 0x46, 0x33, 0x4f, 0x2e, 0xdd, 0x30, 0x7e, 0x04, 0x83, 0x5a,
	0x4d, 0x25, 0x87, 0xe9, 0x56, 0x45, 0x47, 0xa3, 0x7d, 0x74, 0xba, 0xb3, 0x65, 0xf2, 0xd9, 0x19,
	0x1e, 0x52, 0x34, 0xe1, 0x40, 0xd7, 0xf1, 0xd7, 0x6f, 0x6d, 0x93, 0x70, 0xd8, 0xac, 0xe3, 0xbc,
	0xe7, 0x6f, 0xbc, 0xfb, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe6, 0x64, 0x50, 0x7e, 0x01, 0x00,
	0x00,
}
