// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/mfa/v1/get_delivery_options.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeliveryOptionsRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeliveryOptionsRequest) Reset()         { *m = GetDeliveryOptionsRequest{} }
func (m *GetDeliveryOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryOptionsRequest) ProtoMessage()    {}
func (*GetDeliveryOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{0}
}

func (m *GetDeliveryOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Unmarshal(m, b)
}
func (m *GetDeliveryOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Marshal(b, m, deterministic)
}
func (m *GetDeliveryOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryOptionsRequest.Merge(m, src)
}
func (m *GetDeliveryOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Size(m)
}
func (m *GetDeliveryOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryOptionsRequest proto.InternalMessageInfo

func (m *GetDeliveryOptionsRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetDeliveryOptionsResponse struct {
	CodeId               string               `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CodeOptions          *CodeDeliveryOptions `protobuf:"bytes,2,opt,name=code_options,json=codeOptions,proto3" json:"code_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDeliveryOptionsResponse) Reset()         { *m = GetDeliveryOptionsResponse{} }
func (m *GetDeliveryOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryOptionsResponse) ProtoMessage()    {}
func (*GetDeliveryOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{1}
}

func (m *GetDeliveryOptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Unmarshal(m, b)
}
func (m *GetDeliveryOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetDeliveryOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryOptionsResponse.Merge(m, src)
}
func (m *GetDeliveryOptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Size(m)
}
func (m *GetDeliveryOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryOptionsResponse proto.InternalMessageInfo

func (m *GetDeliveryOptionsResponse) GetCodeId() string {
	if m != nil {
		return m.CodeId
	}
	return ""
}

func (m *GetDeliveryOptionsResponse) GetCodeOptions() *CodeDeliveryOptions {
	if m != nil {
		return m.CodeOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDeliveryOptionsRequest)(nil), "alpacalabs.mfa.v1.GetDeliveryOptionsRequest")
	proto.RegisterType((*GetDeliveryOptionsResponse)(nil), "alpacalabs.mfa.v1.GetDeliveryOptionsResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/mfa/v1/get_delivery_options.proto", fileDescriptor_76da31904b53232f)
}

var fileDescriptor_76da31904b53232f = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x49, 0xcc, 0x29, 0x48,
	0x4c, 0x4e, 0xcc, 0x49, 0x4c, 0x2a, 0xd6, 0xcf, 0x4d, 0x4b, 0xd4, 0x2f, 0x33, 0xd4, 0x4f, 0x4f,
	0x2d, 0x89, 0x4f, 0x49, 0xcd, 0xc9, 0x2c, 0x4b, 0x2d, 0xaa, 0x8c, 0xcf, 0x2f, 0x28, 0xc9, 0xcc,
	0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x44, 0xa8, 0xd6, 0xcb, 0x4d, 0x4b,
	0xd4, 0x2b, 0x33, 0x94, 0xd2, 0xc5, 0x34, 0x20, 0x39, 0x3f, 0x25, 0x15, 0x87, 0x09, 0x4a, 0x56,
	0x5c, 0x92, 0xee, 0xa9, 0x25, 0x2e, 0x50, 0x49, 0x7f, 0x88, 0x5c, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x90, 0x2c, 0x17, 0x57, 0x62, 0x72, 0x72, 0x7e, 0x69, 0x5e, 0x49, 0x7c, 0x66, 0x8a,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x54, 0xc4, 0x33, 0x45, 0xa9, 0x81, 0x91, 0x4b,
	0x0a, 0x9b, 0xe6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x71, 0x2e, 0x76, 0xb0, 0xcd, 0x70,
	0xad, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x27, 0x17, 0x0f, 0x58, 0x02, 0xea, 0x12, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0x6e, 0x23, 0x35, 0x3d, 0x0c, 0xcf, 0xe8, 0x39, 0xe7, 0xa7, 0xa4, 0xa2, 0x1b,
	0xcf, 0x0d, 0xd2, 0x0b, 0xe5, 0x38, 0x75, 0x33, 0x72, 0x89, 0x26, 0xe7, 0xe7, 0x62, 0x6a, 0x75,
	0xe2, 0xf0, 0x4d, 0x4b, 0x0c, 0x00, 0x79, 0x31, 0x80, 0x31, 0xca, 0x22, 0x3d, 0xb3, 0x24, 0xa3,
	0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0x11, 0xac, 0xd2, 0x07, 0x14, 0x3c, 0xe0, 0x10, 0x28,
	0x4a, 0x2d, 0xc8, 0xd7, 0xcd, 0x4d, 0x4b, 0xd4, 0x4d, 0xcf, 0xd7, 0xc7, 0x08, 0xba, 0x45, 0x4c,
	0xcc, 0x8e, 0x3e, 0xbe, 0xab, 0x98, 0x04, 0x11, 0xba, 0xf4, 0x7c, 0xd3, 0x12, 0xf5, 0xc2, 0x0c,
	0x4f, 0x21, 0x8b, 0xc5, 0xf8, 0xa6, 0x25, 0xc6, 0x84, 0x19, 0x26, 0xb1, 0x81, 0x4d, 0x34, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0xcf, 0xa7, 0x0c, 0xc5, 0x01, 0x00, 0x00,
}
