// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/mfa/v1/get_delivery_options.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetDeliveryOptionsRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeliveryOptionsRequest) Reset()         { *m = GetDeliveryOptionsRequest{} }
func (m *GetDeliveryOptionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryOptionsRequest) ProtoMessage()    {}
func (*GetDeliveryOptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{0}
}

func (m *GetDeliveryOptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Unmarshal(m, b)
}
func (m *GetDeliveryOptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Marshal(b, m, deterministic)
}
func (m *GetDeliveryOptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryOptionsRequest.Merge(m, src)
}
func (m *GetDeliveryOptionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryOptionsRequest.Size(m)
}
func (m *GetDeliveryOptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryOptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryOptionsRequest proto.InternalMessageInfo

func (m *GetDeliveryOptionsRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetDeliveryOptionsResponse struct {
	CodeId               string       `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CodeOptions          *CodeOptions `protobuf:"bytes,2,opt,name=code_options,json=codeOptions,proto3" json:"code_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDeliveryOptionsResponse) Reset()         { *m = GetDeliveryOptionsResponse{} }
func (m *GetDeliveryOptionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeliveryOptionsResponse) ProtoMessage()    {}
func (*GetDeliveryOptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{1}
}

func (m *GetDeliveryOptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Unmarshal(m, b)
}
func (m *GetDeliveryOptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Marshal(b, m, deterministic)
}
func (m *GetDeliveryOptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeliveryOptionsResponse.Merge(m, src)
}
func (m *GetDeliveryOptionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeliveryOptionsResponse.Size(m)
}
func (m *GetDeliveryOptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeliveryOptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeliveryOptionsResponse proto.InternalMessageInfo

func (m *GetDeliveryOptionsResponse) GetCodeId() string {
	if m != nil {
		return m.CodeId
	}
	return ""
}

func (m *GetDeliveryOptionsResponse) GetCodeOptions() *CodeOptions {
	if m != nil {
		return m.CodeOptions
	}
	return nil
}

type PhoneNumberOption struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// associated account
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneNumberOption) Reset()         { *m = PhoneNumberOption{} }
func (m *PhoneNumberOption) String() string { return proto.CompactTextString(m) }
func (*PhoneNumberOption) ProtoMessage()    {}
func (*PhoneNumberOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{2}
}

func (m *PhoneNumberOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumberOption.Unmarshal(m, b)
}
func (m *PhoneNumberOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumberOption.Marshal(b, m, deterministic)
}
func (m *PhoneNumberOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumberOption.Merge(m, src)
}
func (m *PhoneNumberOption) XXX_Size() int {
	return xxx_messageInfo_PhoneNumberOption.Size(m)
}
func (m *PhoneNumberOption) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumberOption.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumberOption proto.InternalMessageInfo

func (m *PhoneNumberOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PhoneNumberOption) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *PhoneNumberOption) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type EmailAddressOption struct {
	// primary key
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// associated account
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// actual value
	EmailAddress         string   `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailAddressOption) Reset()         { *m = EmailAddressOption{} }
func (m *EmailAddressOption) String() string { return proto.CompactTextString(m) }
func (*EmailAddressOption) ProtoMessage()    {}
func (*EmailAddressOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{3}
}

func (m *EmailAddressOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailAddressOption.Unmarshal(m, b)
}
func (m *EmailAddressOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailAddressOption.Marshal(b, m, deterministic)
}
func (m *EmailAddressOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailAddressOption.Merge(m, src)
}
func (m *EmailAddressOption) XXX_Size() int {
	return xxx_messageInfo_EmailAddressOption.Size(m)
}
func (m *EmailAddressOption) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailAddressOption.DiscardUnknown(m)
}

var xxx_messageInfo_EmailAddressOption proto.InternalMessageInfo

func (m *EmailAddressOption) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailAddressOption) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *EmailAddressOption) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

type CodeOptions struct {
	PhoneNumbers         []*PhoneNumberOption  `protobuf:"bytes,1,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	EmailAddresses       []*EmailAddressOption `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CodeOptions) Reset()         { *m = CodeOptions{} }
func (m *CodeOptions) String() string { return proto.CompactTextString(m) }
func (*CodeOptions) ProtoMessage()    {}
func (*CodeOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_76da31904b53232f, []int{4}
}

func (m *CodeOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeOptions.Unmarshal(m, b)
}
func (m *CodeOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeOptions.Marshal(b, m, deterministic)
}
func (m *CodeOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeOptions.Merge(m, src)
}
func (m *CodeOptions) XXX_Size() int {
	return xxx_messageInfo_CodeOptions.Size(m)
}
func (m *CodeOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CodeOptions proto.InternalMessageInfo

func (m *CodeOptions) GetPhoneNumbers() []*PhoneNumberOption {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func (m *CodeOptions) GetEmailAddresses() []*EmailAddressOption {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDeliveryOptionsRequest)(nil), "alpacalabs.mfa.v1.GetDeliveryOptionsRequest")
	proto.RegisterType((*GetDeliveryOptionsResponse)(nil), "alpacalabs.mfa.v1.GetDeliveryOptionsResponse")
	proto.RegisterType((*PhoneNumberOption)(nil), "alpacalabs.mfa.v1.PhoneNumberOption")
	proto.RegisterType((*EmailAddressOption)(nil), "alpacalabs.mfa.v1.EmailAddressOption")
	proto.RegisterType((*CodeOptions)(nil), "alpacalabs.mfa.v1.CodeOptions")
}

func init() {
	proto.RegisterFile("alpacalabs/mfa/v1/get_delivery_options.proto", fileDescriptor_76da31904b53232f)
}

var fileDescriptor_76da31904b53232f = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x03, 0x4d, 0xae, 0xde, 0x03, 0xf7, 0x9a, 0x4e, 0x62, 0x44, 0x13, 0x4d, 0x45, 0x4d,
	0xba, 0xb0, 0x43, 0xa8, 0x1b, 0xe3, 0x8e, 0xaa, 0x31, 0x4d, 0x4a, 0x6d, 0x58, 0x74, 0x61, 0x9a,
	0x90, 0x81, 0x39, 0xb4, 0x24, 0xc0, 0x20, 0x03, 0x8d, 0x3e, 0x83, 0x6f, 0xe1, 0xca, 0xf8, 0x28,
	0x3e, 0x95, 0x81, 0xa2, 0x60, 0xe9, 0xca, 0xe5, 0x9c, 0xf9, 0xcf, 0x77, 0xfe, 0x73, 0xf2, 0xc3,
	0x4b, 0x96, 0xe4, 0x2c, 0x64, 0x09, 0x0b, 0xa4, 0x95, 0x46, 0xcc, 0x3a, 0xda, 0xd6, 0x1e, 0x4b,
	0x9f, 0x63, 0x12, 0x1f, 0xb1, 0xf8, 0xea, 0x8b, 0xbc, 0x8c, 0x45, 0x26, 0x69, 0x5e, 0x88, 0x52,
	0x90, 0x71, 0xa7, 0xa6, 0x69, 0xc4, 0xe8, 0xd1, 0x36, 0xdf, 0xc0, 0xc3, 0x0f, 0x58, 0xbe, 0x6b,
	0xf5, 0x1f, 0x4f, 0x72, 0x0f, 0x3f, 0x57, 0x28, 0x4b, 0xf2, 0x18, 0x80, 0x85, 0xa1, 0xa8, 0xb2,
	0xd2, 0x8f, 0xb9, 0xa1, 0x4c, 0x94, 0xe9, 0xb5, 0x77, 0xdd, 0x56, 0x96, 0xdc, 0xfc, 0x02, 0x8f,
	0x2e, 0xf5, 0xca, 0x5c, 0x64, 0x12, 0xc9, 0x03, 0xb8, 0x13, 0x0a, 0x8e, 0x5d, 0xe7, 0x55, 0xfd,
	0x5c, 0x72, 0xe2, 0x80, 0xde, 0x7c, 0xb4, 0xde, 0x0c, 0x75, 0xa2, 0x4c, 0xb5, 0xf9, 0x13, 0x3a,
	0x30, 0x47, 0xdf, 0x0a, 0x8e, 0x7f, 0xb0, 0x5a, 0xd8, 0x3d, 0x4c, 0x84, 0xf1, 0xe6, 0x20, 0x32,
	0x5c, 0x57, 0x69, 0x80, 0xc5, 0xa9, 0x4a, 0x6e, 0x41, 0xfd, 0x3b, 0x4b, 0x8d, 0xf9, 0x99, 0x7b,
	0xf5, 0xcc, 0x3d, 0x79, 0x0a, 0x7a, 0x5e, 0x33, 0xfc, 0xac, 0x81, 0x18, 0xa3, 0x46, 0xa0, 0xe5,
	0x1d, 0xd7, 0x3c, 0x00, 0x79, 0x9f, 0xb2, 0x38, 0x71, 0x38, 0x2f, 0x50, 0xca, 0xff, 0x9b, 0xf3,
	0x0c, 0x6e, 0xb0, 0x86, 0xf8, 0xec, 0x44, 0x69, 0x07, 0xe9, 0xd8, 0x23, 0x9b, 0x3f, 0x14, 0xd0,
	0x7a, 0xdb, 0x92, 0x25, 0xdc, 0xf4, 0xcd, 0x49, 0x43, 0x99, 0x8c, 0xa6, 0xda, 0xfc, 0xf9, 0x85,
	0x23, 0x0d, 0x0e, 0xe1, 0xe9, 0xbd, 0x1d, 0x24, 0x59, 0xc3, 0xbd, 0x7f, 0xe6, 0x63, 0x7d, 0xf1,
	0x1a, 0xf6, 0xe2, 0x02, 0x6c, 0xb8, 0xae, 0x77, 0xdb, 0x37, 0x8a, 0x72, 0xf1, 0x4d, 0x81, 0xfb,
	0xa1, 0x48, 0x87, 0xcd, 0x8b, 0xbb, 0x6e, 0xc4, 0x36, 0x75, 0xd0, 0x36, 0xca, 0xa7, 0xd7, 0xfb,
	0xb8, 0x3c, 0x54, 0x01, 0x0d, 0x45, 0x6a, 0x39, 0x8d, 0x72, 0x55, 0x67, 0xb4, 0xc9, 0x61, 0x81,
	0xb9, 0x98, 0xa5, 0x11, 0x9b, 0xed, 0x85, 0x35, 0xc8, 0xef, 0x77, 0x75, 0xe4, 0xac, 0xdc, 0x9f,
	0xea, 0xb8, 0xeb, 0xa2, 0x6e, 0xc4, 0xe8, 0xd6, 0xfe, 0xd5, 0xaf, 0xed, 0xdc, 0x88, 0xed, 0xb6,
	0x76, 0x70, 0xd5, 0x10, 0x5f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x28, 0x2e, 0x80, 0x08, 0x09,
	0x03, 0x00, 0x00,
}
