// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/mfa/v1/send_code.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendCodeRequest struct {
	// foreign key referencing code
	CodeId    string `protobuf:"bytes,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Types that are valid to be assigned to DeviceId:
	//	*SendCodeRequest_EmailAddressId
	//	*SendCodeRequest_PhoneNumberId
	DeviceId             isSendCodeRequest_DeviceId `protobuf_oneof:"device_id"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SendCodeRequest) Reset()         { *m = SendCodeRequest{} }
func (m *SendCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendCodeRequest) ProtoMessage()    {}
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b55f16112317a6, []int{0}
}

func (m *SendCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeRequest.Unmarshal(m, b)
}
func (m *SendCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeRequest.Merge(m, src)
}
func (m *SendCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendCodeRequest.Size(m)
}
func (m *SendCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeRequest proto.InternalMessageInfo

func (m *SendCodeRequest) GetCodeId() string {
	if m != nil {
		return m.CodeId
	}
	return ""
}

func (m *SendCodeRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type isSendCodeRequest_DeviceId interface {
	isSendCodeRequest_DeviceId()
}

type SendCodeRequest_EmailAddressId struct {
	EmailAddressId string `protobuf:"bytes,3,opt,name=email_address_id,json=emailAddressId,proto3,oneof"`
}

type SendCodeRequest_PhoneNumberId struct {
	PhoneNumberId string `protobuf:"bytes,4,opt,name=phone_number_id,json=phoneNumberId,proto3,oneof"`
}

func (*SendCodeRequest_EmailAddressId) isSendCodeRequest_DeviceId() {}

func (*SendCodeRequest_PhoneNumberId) isSendCodeRequest_DeviceId() {}

func (m *SendCodeRequest) GetDeviceId() isSendCodeRequest_DeviceId {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *SendCodeRequest) GetEmailAddressId() string {
	if x, ok := m.GetDeviceId().(*SendCodeRequest_EmailAddressId); ok {
		return x.EmailAddressId
	}
	return ""
}

func (m *SendCodeRequest) GetPhoneNumberId() string {
	if x, ok := m.GetDeviceId().(*SendCodeRequest_PhoneNumberId); ok {
		return x.PhoneNumberId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SendCodeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SendCodeRequest_EmailAddressId)(nil),
		(*SendCodeRequest_PhoneNumberId)(nil),
	}
}

type SendCodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeResponse) Reset()         { *m = SendCodeResponse{} }
func (m *SendCodeResponse) String() string { return proto.CompactTextString(m) }
func (*SendCodeResponse) ProtoMessage()    {}
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_39b55f16112317a6, []int{1}
}

func (m *SendCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeResponse.Unmarshal(m, b)
}
func (m *SendCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeResponse.Marshal(b, m, deterministic)
}
func (m *SendCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeResponse.Merge(m, src)
}
func (m *SendCodeResponse) XXX_Size() int {
	return xxx_messageInfo_SendCodeResponse.Size(m)
}
func (m *SendCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendCodeRequest)(nil), "alpacalabs.mfa.v1.SendCodeRequest")
	proto.RegisterType((*SendCodeResponse)(nil), "alpacalabs.mfa.v1.SendCodeResponse")
}

func init() { proto.RegisterFile("alpacalabs/mfa/v1/send_code.proto", fileDescriptor_39b55f16112317a6) }

var fileDescriptor_39b55f16112317a6 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x4d, 0x2b, 0xd5, 0xae, 0x68, 0xdb, 0x80, 0xe8, 0x45, 0xd0, 0x9e, 0x8a, 0xd0, 0x0d,
	0xc1, 0x8b, 0xd7, 0xd6, 0x8b, 0x81, 0x46, 0x4a, 0x85, 0x1e, 0xa4, 0x10, 0x26, 0x3b, 0x93, 0x36,
	0xd0, 0xdd, 0x8d, 0xd9, 0xa4, 0x2f, 0xe1, 0x5b, 0x78, 0x14, 0x9f, 0xc4, 0xa7, 0x92, 0x5d, 0x0b,
	0x11, 0x7a, 0xdc, 0xff, 0xfb, 0x66, 0x99, 0xf9, 0xd9, 0x1d, 0x6c, 0x0b, 0x10, 0xb0, 0x85, 0xd4,
	0x04, 0x32, 0x83, 0x60, 0x17, 0x06, 0x86, 0x14, 0x26, 0x42, 0x23, 0xf1, 0xa2, 0xd4, 0x95, 0xf6,
	0x07, 0x8d, 0xc2, 0x65, 0x06, 0x7c, 0x17, 0x0e, 0xbf, 0x3d, 0xd6, 0x7b, 0x25, 0x85, 0x4f, 0x1a,
	0x69, 0x41, 0xef, 0x35, 0x99, 0xca, 0xbf, 0x62, 0x27, 0x76, 0x28, 0xc9, 0xf1, 0xda, 0xbb, 0xf5,
	0x46, 0xdd, 0x45, 0xc7, 0x3e, 0x23, 0xf4, 0x6f, 0x18, 0x03, 0x21, 0x74, 0xad, 0x2a, 0xcb, 0x5a,
	0x8e, 0x75, 0xf7, 0x49, 0x84, 0xfe, 0x3d, 0xeb, 0x93, 0x84, 0x7c, 0x9b, 0x00, 0x62, 0x49, 0xc6,
	0x58, 0xa9, 0x6d, 0xa5, 0xe7, 0xa3, 0xc5, 0x85, 0x23, 0x93, 0x3f, 0x10, 0xa1, 0x3f, 0x62, 0xbd,
	0x62, 0xa3, 0x15, 0x25, 0xaa, 0x96, 0x29, 0x95, 0x56, 0x3d, 0xde, 0xab, 0xe7, 0x0e, 0xbc, 0xb8,
	0x3c, 0xc2, 0xe9, 0x19, 0xeb, 0x22, 0xed, 0x72, 0x61, 0xf7, 0x19, 0xfa, 0xac, 0xdf, 0x6c, 0x6b,
	0x0a, 0xad, 0x0c, 0x4d, 0x3f, 0x3c, 0x76, 0x29, 0xb4, 0xe4, 0x07, 0xc7, 0x4d, 0x4f, 0xe3, 0x0c,
	0xe6, 0xf6, 0xf2, 0xb9, 0xf7, 0xf6, 0xb8, 0xce, 0xab, 0x4d, 0x9d, 0x72, 0xa1, 0x65, 0x30, 0x71,
	0xe6, 0xcc, 0x36, 0xe5, 0x8a, 0x29, 0xa9, 0xd0, 0x63, 0x99, 0xc1, 0x78, 0xad, 0x83, 0x83, 0x16,
	0x3f, 0x5b, 0xed, 0xc9, 0x2c, 0xfe, 0x6a, 0x0d, 0x9a, 0x29, 0x1e, 0x67, 0xc0, 0x97, 0xe1, 0xcf,
	0xff, 0x6c, 0x15, 0x67, 0xb0, 0x5a, 0x86, 0x69, 0xc7, 0xfd, 0xf8, 0xf0, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x26, 0xfd, 0x82, 0x9b, 0x8f, 0x01, 0x00, 0x00,
}
